### ISSUE TITLE
InternalError Metro has encountered an error: Indeed, none of these files exist:

### ISSUE THREAD

**Issue by emmanuelOpara777** [yuri-becker/react-jigsaw-puzzle#1]
I just added this package to my project but it's returning this error upon running my application.

[Error: InternalError Metro has encountered an error: While trying to resolve module `react-jigsaw-puzzle` from file `C:\Users\dell\Desktop\jigsaw\App.js`, the package `C:\Users\dell\Desktop\jigsaw\node_modules\react-jigsaw-puzzle\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\dell\Desktop\jigsaw\node_modules\react-jigsaw-puzzle\lib\src\index.js`. Indeed, none of these files exist:

I checked this folder: node_modules\react-jigsaw-puzzle\lib\src\index.js and discovered that it does not exist.
Please I need help on how to resolve this issue.

Thank you in advance.

**Comment by yuri-becker** [comment]
Hi Emmanuel,

thank you for filing an issue. I fixed the main file declaration in the package.json and published it as 1.0.2 to npm. Please let me know if that resolved your problem.

**Comment by emmanuelOpara777** [comment]
@yuri-becker thanks for your quick response.
The error message changed to:
[Error: undefined Unable to resolve module **./jigsaw-puzzle.css** from **...\jigsaw\node_modules\react-jigsaw-puzzle\lib\jigsaw-puzzle.js:**
![image](https://user-images.githubusercontent.com/32057585/130478004-07dfd329-5271-4a69-aa9b-5d819660b689.png)

**Comment by yuri-becker** [comment]
Im not sure about this one. The css file should definitely be there. Does Metro support css?

**Comment by emmanuelOpara777** [comment]
@yuri-becker the CSS file is there but it's not seeing it. I don't know if Metro Bundler supports CSS or not.

**Comment by SHANbic** [comment]
Im using next.js for my app and I want to add a puzzle game using react-jigsaw-puzzle. Im also getting an error and from the next documentation, here's how to address the issue: 

_Compiled dependencies do not have references to CSS files, or any other files that require bundler-specific integrations._

_The dependency should also provide instructions about what CSS needs to be imported by you, in your application._

_Importing CSS files within node_modules cannot be supported because we cannot know the correct behavior:_

_Should the file be consumed as Global CSS or CSS Modules?_
_If Global, in what order does the file need to be injected?_
_If Modules, what are the emitted class names? As-is, camel-case, snake case?_
_Etc..._

The same doc states that the maintainer should publish a compiled version of his/her dependency.

[https://nextjs.org/docs/messages/css-npm](https://nextjs.org/docs/messages/css-npm
)

Hope this helps @yuri-becker

**Comment by yuri-becker** [comment]
Hi @SHANbic,

thank you very much for the information. I will update the package later today.

**Comment by yuri-becker** [comment]
@SHANbic @emmanuelOpara777 I've removed the CSS import from inside the module. Let me know if that fixed your problem.

**Comment by emmanuelOpara777** [comment]
@yuri-becker that did not fix it. Recent error message: 
**Unable to resolve module react-jigsaw-puzzle/lib/jigsaw-puzzle.css from ...\jigsaw\App.js: react-jigsaw-puzzle/lib/jigsaw-puzzle.css could not be found within the project or in these directories:
  node_modules**

**Comment by yuri-becker** [comment]
@emmanuelOpara777 The CSS file should be there. Can you check that?

**Comment by SHANbic** [comment]
@yuri-becker thx its all good now!
@emmanuelOpara777  did you update the dependency version in your package.json?
